### PR TITLE
Support format

### PR DESCRIPTION
**Pull request by TugdualSarazin**
Support formats:
* int64 -> Long
* int32 -> Int
* int16 -> Short
* int8 -> Byte
* single -> Float
* double -> Double
* uuid -> java.util.UUID
* date-time -> org.joda.time.DateTime

### CODE REVIEW

**Comment by TugdualSarazin** [comment]
DateTime is based on joda but perhaps it's a better idea to use java ZonedDateTime?

**Comment by tscholak** [comment]
@TugdualSarazin :+1: for ZonedDateTime

**Comment by tscholak** [comment]
@TugdualSarazin @aishfenton I had some free time and made a PR here: https://github.com/flamefy/Argus/pull/1

**Comment by TugdualSarazin** [comment]
Is there a problem with this PR?

**Comment by tscholak** [comment]
bump

**Comment by tscholak** [comment]
Bumpy McBumpface

**Comment by aishfenton** [comment]
Sorry for very dormant responses to this. Merging now.

**Pull request merged**
